### ISSUE TITLE
Invitation to collaborate.

### ISSUE THREAD

**Issue by asking28** [talhaanwarch/DeftEval2020#1]
I am working on same competitions. I have F1 macro of 0.80 in offenseval task. Please let me know if you wish to work together. Thanks

**Comment by talhaanwarch** [comment]
Hi, Abhishek Singh, actually i am more focusing one offenseval task than defteval. defteval task is ending on 10 january and i dont think i can get some time for it. 
Where as i have a lot of time for offenseval and my f1 macro is 0.77 yet

**Comment by asking28** [comment]
Okay, no problem. Defteval has extended their dates by the way, same as other tasks. We can work on Offenseval, let me know.

**Comment by talhaanwarch** [comment]
sure we can work, please check my[ offenseval repo.](https://github.com/talhaanwarch/Offensive-Language-Detection)

**Comment by talhaanwarch** [comment]
one more thing, i am not an expert, i am just learning things
